### PR TITLE
Add Errors objects into PluginContext

### PR DESCRIPTION
**Pull request by stafyniaksacha**
Add Errors objects into PluginContext

### CODE REVIEW

**Comment by scottinet** [comment]
uh... errors are shared, too. They are simply dynamically searched. Or at least they were, but since these objects have been moved into the `kuzzle-common-objects` module, the filesystem search fails and there is no error objects to be exposed in the context.

So I suggest we fix the dynamic error objects exposure instead of removing `RequestObject` and `ResponseObject` objects.

**Comment by ballinette** [comment]
PR title should be updated, because now, we do not remove RequestObject & ResponseObject, but we add Error objects ;)

But +1 for this new version ;)

**Comment by scottinet** [comment]
+1!

**Comment by benoitvidis** [comment]
Hum... If I am not mistaken, the current implementation breaks the previous implementation where the Error objects were put at the root level.
I agree that we may need to update the plugin context structure, as discussed in #292. 

I suppose we first need to decide if we change the plugin context structure and if so, agree on the new formatting before we update all Kuzzle plugins.

**Comment by scottinet** [comment]
Ah, didn't think of that. I agree with @benoitvidis, let's hold this one until our (little) workshop about the plugins context structure.

**Comment by scottinet** [comment]
Closing this PR, I'll prepare another branch with a new plugin context structure.

**Pull request closed without merging**
