### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
:warning: Don't merge this PR even if there is 3 reviewers approval :warning: (@aschen)

Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/kuzzleio/kuzzle/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/kuzzleio/kuzzle).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by xcorail** [comment]
Hi @scottinet 
Thanks for your review. 

As for the alert that you identified as false positive 
It says "**Variable 'isValid'** always evaluates to true here" 

```
var
 isValid = true,
 errorMessages = verbose ? {} : [];
  
 if (collectionSpec) {
   if (collectionSpec.fields && collectionSpec.fields.children) {
     try {
       isValid = isValid && this.recurseFieldValidation(documentBody, collectionSpec.fields.children, collectionSpec.strict, errorMessages, verbose);

```
The alert basically says that the last line could have been written:
```
isValid = this.recurseFieldValidation(documentBody, collectionSpec.fields.children, collectionSpec.strict, errorMessages, verbose);
```
Usually, the presence of a test `true && condition` indicates an incomplete code. I agree that it's not the case in this code. Perhaps there was in the past some code changing this `isValid` value before this line, that has been removed since. 

Cheers

**Comment by scottinet** [comment]
You're right, this can (and should) be simplified. 
Frankly, I should've seen that right away :confused:

**Comment by xcorail** [comment]
Oh, I forgot to mention that you can also activate Pull Request integration [here](https://lgtm.com/projects/g/kuzzleio/kuzzle/ci/). The same analysis will run within each PR and will report if new problems are found or if old problems get fixed. 
Still free, still little to no effort.

**Comment by Aschen** [comment]
I really like the PR integration because actually Sonarqube is only launch by travis and he didn't appear in the check list.

image

**Comment by ballinette** [comment]
Thx @xcorail

**Comment by Aschen** [comment]
@xcorail There is something I didn't understand about the codebase analysed. [Here](https://lgtm.com/projects/g/kuzzleio/kuzzle/alerts/?mode=list) I can see that there 5 alerts but they refer to an old codebase. ([kuzzle/rev/765afe87dbcd642ffb40b8b2c5d61aab471aad12](https://lgtm.com/projects/g/kuzzleio/kuzzle/rev/765afe87dbcd642ffb40b8b2c5d61aab471aad12))
LGTM is not supposed to run on master ?

**Comment by xcorail** [comment]
Hey @Aschen 
Indeed ... there are flat lines on both code and alerts for 1 year and a half ... How did we miss this?
This usually happens when the default branch is changed. Fairly soon, the system will automatically detect this and switch to the default branch, but for now our support team will fix it on our end.
Can you confirm this is what happened?

**Comment by scottinet** [comment]
@xcorail > we actually switched our default branch around that date, so that must be it. :+1:

**Comment by xcorail** [comment]
Ok, so our support team is on it as we speak. However the new results will take some time to show up. The most recent will appear first, then it will go back through history

**Pull request merged**
