### PR TITLE
Protocol plugins prerequisites

### PR DESCRIPTION
**Pull request by scottinet**
*  The router controller now directly respond to requesters, without using the notifier core component anymore. This is to set clients<=>router communication apart from the rest of Kuzzle, making easier to implement protocol plugins
* The notifier core component now only broadcasts messages and does not accept a connection argument, since the router now respond directly to clients
* Added the new api/serverInfo route. The main goal is to provide requesters with the API version of Kuzzle, ensuring that plugins and SDKs are compatible. This command also returns a lot of useful informations about Kuzzle, its plugins, the system and active services.
* Added unit and functional tests
* Split the functional tests keywords implementation into multiple files in order to clean things up

### CODE REVIEW

**Comment by j33f** [comment]
+1

**Comment by stafyniaksacha** [comment]
+1

**Comment by AnthonySendra** [comment]
+1
(thanks for splitting `step_definitions` files ...)

**Comment by ballinette** [comment]
+1

**Pull request merged**
