### PR TITLE
[release-1.0.0-RC3] Add Errors objects into PluginContext

### PR DESCRIPTION
**Pull request by ballinette**
move PR #303  to release 1.0.0-RC3
(see comments within the original PR)

### CODE REVIEW

**Comment by scottinet** [comment]
+1

**Comment by j33f** [comment]
:+1:

**Comment by ballinette** [comment]
following comments on #303, I suggest to postpone the merge for now, until we have fixed the plugins context format.

**Comment by scottinet** [comment]
I have a urgent need to refactor the plugins context: I need it to be a *class*, not a function returning an object.

So in my next hotfix, I'm gonna start from this PR branch, and proposing a flattened structure containing model objects (RequestObject, Errors, and so on), and the lazy-loaders as properties of this class.

**Comment by scottinet** [comment]
Ok I discussed this issue with @benoitvidis 

What I propose is this:
* I change the pull request on the **release branch** to fix error constructors not being in the context due to error constructors being moved in a node module
* I change the pull request on the **develop branch** to propose a new plugin context structure and to change it to a "class"
* I update existing plugins with the new context structure

**Comment by scottinet** [comment]
Done. This PR can be reviewed, it will be on par with what plugins currently expect.

**Comment by ballinette** [comment]
Why NotificationObject has gone away ?

**Comment by scottinet** [comment]
It is meant to be used only by the `notifier` core component. Since plugins cannot send notifications nor access to this component, I don't see why it should be exposed.

**Comment by ballinette** [comment]
OK, LGTM

**Comment by benoitvidis** [comment]
+1

**Comment by xbill82** [comment]
+1

**Pull request merged**
