### PR TITLE
Rename loadbalancer as proxy in all docker compose and base it on new image names

### PR DESCRIPTION
**Pull request by dbengsch**

### CODE REVIEW

**Comment by stafyniaksacha** [comment]
+1

**Comment by ballinette** [comment]
+1
Just to be sure: do we also plan to rename LB "entry point" and LB broker ?

**Comment by dbengsch** [comment]
@ballinette : I think so, but I must admit I only cared about the docker images consistency in these changes.

**Comment by jenow** [comment]
+1

**Pull request merged**
