### PR TITLE
Add current commit to server:info

### PR DESCRIPTION
**Pull request by Aschen**
## What does this PR do ?

Try to retrieve the current commit and expose it in the `server:info` action.

image

I know that not every project will be able to use this feature because people can use another CVS (very unlikely) or they will deploy Kuzzle without the `.git` directory (likely).  
But at least people that deploy Kuzzle with the `.git` directory will be able to see the commit hash.

### CODE REVIEW

**Review by scottinet — APPROVED** [review]
Should be tremendously useful when doing client support :+1:

**Comment by Aschen** [comment]
> Should be tremendously useful when doing client support +1

It's not Kuzzle commit, it's the client application commit. Is that what you understood ?

**Comment by scottinet** [comment]
Of course (we already have the kuzzle "commit" because server:info gives the current kuzzle version)

**Review by alexandrebouthinon — COMMENTED** [review]
the code LGTM but you need to update Dockerfile to copy the `.git` directory in the builded image

**Comment by Aschen** [comment]
> the code LGTM but you need to update Dockerfile to copy the `.git` directory in the builded image

Why ? The purpose is not to display Kuzzle commit but the current commit of the application built with Kuzzle

**Review by alexandrebouthinon — APPROVED** [review]

**Pull request merged**
