### PR TITLE
Upgrade koncorde to 4.0.3

### PR DESCRIPTION
**Pull request by Shiranuit**
## What does this PR do ?

Upgrade koncorde version to 4.0.3

ci-allow-merge-into: master

### CODE REVIEW

**Comment by kuzzle** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Found some issues !</td>
    </tr>
  </tbody>
</table>



## Executed Checks

### :warning: Branch Merge Check

```
Bypassed
```

### :x: Changelog Tag Check

Pull Requests must have a `changelog:XXX` label.
If you want to allow this PR to not have a changelog tag, add the following line to the PR body:


```
ci-no-changelog-tag
```

### :heavy_check_mark: PR Body Check


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 33c467d94c6ef90277cb38be28c267a6664bc71a
</p>

**Review by Aschen — CHANGES_REQUESTED** [review]
The `npm-shrinkwrap.json` file should not be published in the package and the package-lock.json should be versioned for our development needs.

The `npm-shrinkwrap.json` file should only be published for CLI

See https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson

**Review by Aschen — APPROVED** [review]

**Review by Aschen — APPROVED** [review]
Strange, looks like we had something unmerged before

**Comment by Shiranuit** [comment]
> Strange, looks like we had something unmerged before

Those are mainly changes fromt Prettier that were done on master but never merged back in 2-dev

**Review by rolljee — APPROVED** [review]

**Pull request closed without merging**
