### PR TITLE
prepareDB : ad automatic indexes creation from default mapping and fixtures

### PR DESCRIPTION
**Pull request by j33f**

### CODE REVIEW

**Comment by ballinette** [comment]
the PR title "resolve conflict" is not very clear... ?
NB: Be careful, in  docs/installation.md file, you removed the Table of Contents introduced by @scottinet  in commit ce68125f719dfc542127c241d735582d8d635e2d

**Comment by j33f** [comment]
@ballinette done

**Comment by ballinette** [comment]
ok
+1

**Comment by jenow** [comment]
+1

**Pull request merged**
