### PR TITLE
Kuz315 api documentation

### PR DESCRIPTION
**Pull request by benoitvidis**
The new doc is online on http://kuzzleio.github.io/kuzzle-api-documentation

May be worth validating at the same time as this PR.

### CODE REVIEW

**Comment by ballinette** [comment]
+1 and great, I will be able to document the authentication mechanism with that ;)

**Comment by scottinet** [comment]
Thanks A LOT for doing this work, it really doesn't seem fun.
The API documentation is now much more organized, and it's a breeze to update it, we really needed that!

+1 obviously

**Comment by jenow** [comment]
+1
Now I can even give url to the slate into the sdk code documentation for the user to have a nice documentation display :)

**Comment by stafyniaksacha** [comment]
+1

**Pull request merged**
