### PR TITLE
Remove filter collection on listCollection once it is allowed in funnel

### PR DESCRIPTION
**Pull request by dbengsch**

### CODE REVIEW

**Comment by j33f** [comment]
+1

**Comment by dbengsch** [comment]
On hold, waiting AnS and SeC to discuss about it.

**Comment by scottinet** [comment]
+1
As discussed this morning, it is way simpler to show collections and let users receive a security error if attempting to perform an unauthorized action on them, than hiding them.

As @ballinette mentioned this morning, it should also be done on the `listIndexes` API route

**Comment by stafyniaksacha** [comment]
Ok for me +1

**Pull request merged**
