### PR TITLE
fix(semantic-release): fix an issue where semver would not satisfies …

### PR DESCRIPTION
**Pull request by rolljee**
…pre-release versions

## What does this PR do ?

This PR allow kuzzle to work with pre release version of plugin and kuzzle itself

### CODE REVIEW

**Review by Kuruyia — APPROVED** [review]

**Comment by Kuruyia** [comment]
Maybe we can add a test for this case?

**Comment by rolljee** [comment]
> Maybe we can add a test for this case?

That's a good idea, I'll do it 👍🏼

**Review by fmauNeko — APPROVED** [review]

**Pull request merged**
