### PR TITLE
Kzl 443 arm

### PR DESCRIPTION
**Pull request by benoitvidis**
**:warning: Depends on https://github.com/kuzzleio/kuzzle-containers/pull/42 + docker hub automation**

## What does this PR do ?

This PR attemps to make Kuzzle arm-friendly.
For the time being, the only uncompatiblity identified is with highwayhash, which targets x85 and amd64 only.

This PR replaces this module in Kuzzle and its dependency with murmurhash3, which seems to be an acceptable candidate for replacement and compiles on arm (no collision seen on several 16M batches and performance is slightly above highwayhash).

### How should this be manually tested?

You can use regular kuzzle tests.

### CODE REVIEW

**Comment by alexandrebouthinon** [comment]
Is this really need to be merge into master ?

**Comment by benoitvidis** [comment]
Travis test added.

**Comment by benoitvidis** [comment]
For some reason, once pushed to docker hub, the arm images do not work on travis.
Needs some further investigation.

**Comment by alexandrebouthinon** [comment]
Need a Travis job splitting to reduce build duration. I'm on it :smile:

**Pull request merged**
