### PR TITLE
Add “suggest” to the whitelisted ES search body keys

### PR DESCRIPTION
**Pull request by pierreminik**
## What does this PR do ?

Adds the [`suggest`](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-suggesters.html) keyword to whitelisted ES search body.

### CODE REVIEW

**Review by Aschen — CHANGES_REQUESTED** [review]
Thanks for your contribution, it's very much appreciated ;-)

Can you also update the documentation to reflect this change ? https://github.com/kuzzleio/kuzzle/blob/master/doc/2/guides/main-concepts/querying/index.md

Also since the result of the `suggest` keyword are not including in the hits array, you will need to add it in the return of the controller action here: https://github.com/kuzzleio/kuzzle/blob/master/lib/api/controllers/documentController.js#L93

**Comment by pierreminik** [comment]
I hope I've done it correctly. 😊

**Comment by Aschen** [comment]
If you could just add/modify an unit test in the document controller, verifying that the `suggest` property from the Elasticsearch result is correctly returned in the document controller action it would be perfect :+1:

**Comment by pierreminik** [comment]
I haven't quite catched how the mocking works so I'm not sure if it's the implementation failing or test not properly test up. I'll figure it out.

**Comment by pierreminik** [comment]
It seems to go through now. I'm not sure if the `suggest` keyword should be available when doing a `scroll` besides the `search`?

**Review by Aschen — APPROVED** [review]

**Comment by Aschen** [comment]
> It seems to go through now. I'm not sure if the `suggest` keyword should be available when doing a `scroll` besides the `search`?

Since the `_formatSearchResult` is used by both `search` and `scroll` it's already available in scroll as well :+1:

**Review by scottinet — APPROVED** [review]

**Pull request merged**
