### PR TITLE
following #kuz-413, local password auth plugin version

### PR DESCRIPTION
**Pull request by benoitvidis**
Needs PR kuzzleio/kuzzle-plugin-auth-passport-local#7 to be merged first

### CODE REVIEW

**Comment by ballinette** [comment]
+1

**Comment by scottinet** [comment]
Dang. I thought I had solved the random unit test failure. I'm working on it.

**Comment by scottinet** [comment]
Unit tests should be fixed now.

**Comment by scottinet** [comment]
+1

**Comment by j33f** [comment]
+1

**Pull request merged**
