### PR TITLE
changed all ES6 Promises to Q

### PR DESCRIPTION
**Pull request by scottinet**
- Changed all ES6 Promises to Q Promises, to guarantee that all promises throughout the Kuzzle code are compatibles.
- Simplified promises management here and there
- Fixed `notifier.publish` unit tests as they did not always had the time to test that redis.expiry has correctly been invoked

### CODE REVIEW

**Comment by scottinet** [comment]
Hm, the code coverage difference comes from covered lines this PR removes. Nothing changed in reality.

**Comment by stafyniaksacha** [comment]
+1

**Comment by jenow** [comment]
+1

**Comment by benoitvidis** [comment]
+1

**Pull request merged**
