### PR TITLE
Fix develop 295 worker does not start correctly

### LINKED ISSUE #295: Kuzzle Worker doesn't start correctly
When starting Kuzzle, If the worker try to connect to the server before the server's initialization is finished, it gets a "ECONNREFUSED" error and should try to reconnect 1 second later, until the connection is established...
This startup feature works well in the **master** branch, but it's broken in the **develop** branch (Maybe a regression with a recent PR ?).

Here are the logs:

```
kuzzle_1 | KuzzleWorker-1 info: [2016-06-03T10:02:08.937Z]: workerGroup:loaded: writeEngine
kuzzle_1 | KuzzleWorker-1 error: [2016-06-03T10:02:09.058Z]: log:error: Error while trying to connect to ws://localhost:7911 [connect ECONNREFUSED 127.0.0.1:7911]
kuzzle_1 | KuzzleWorker-1       ==> RECONNECTING IN 1000ms
kuzzle_1 | KuzzleWorker-1 info: [2016-06-03T10:02:09.063Z]: internalBroker:*:  host=localhost, port=7911, message=connect ECONNREFUSED 127.0.0.1:7911, retry=1000
kuzzle_1 | KuzzleWorker-1 info: [2016-06-03T10:02:09.080Z]: internalBroker:*: Socket closed with code 1006
kuzzle_1 | KuzzleWorker-1       ==> RECONNECTING IN 1000ms
kuzzle_1 | KuzzleServer-0 Plugin kuzzle-plugin-socketio started
kuzzle_1 | KuzzleServer-0 Plugin kuzzle-plugin-auth-passport-local started
kuzzle_1 | KuzzleServer-0 Plugin kuzzle-plugin-logger started
kuzzle_1 | KuzzleServer-0 info: [2016-06-03T10:02:11.599Z]: log:info: Remote Action Controller initialized
kuzzle_1 | KuzzleServer-0       ▄▄▄▄▄      ▄███▄      ▄▄▄▄
kuzzle_1 | KuzzleServer-0    ▄█████████▄▄█████████▄▄████████▄
kuzzle_1 | KuzzleServer-0   ██████████████████████████████████
kuzzle_1 | KuzzleServer-0    ▀██████████████████████████████▀
kuzzle_1 | KuzzleServer-0     ▄███████████████████████████▄
kuzzle_1 | KuzzleServer-0   ▄███████████████████████████████▄
kuzzle_1 | KuzzleServer-0  ▀█████████████████████████████████▀
kuzzle_1 | KuzzleServer-0    ▀██▀        ▀██████▀       ▀██▀
kuzzle_1 | KuzzleServer-0           ██     ████    ██
kuzzle_1 | KuzzleServer-0                 ▄████▄
kuzzle_1 | KuzzleServer-0                 ▀████▀
kuzzle_1 | KuzzleServer-0                   ▀▀
kuzzle_1 | KuzzleServer-0  ████████████████████████████████████
kuzzle_1 | KuzzleServer-0  ██     KUZZLE SERVER STARTED      ██
kuzzle_1 | KuzzleServer-0  ██   ...WAITING FOR WORKERS...    ██
kuzzle_1 | KuzzleServer-0  ████████████████████████████████████
```
... and then, nothing happens

### PR DESCRIPTION
**Pull request by ballinette**
fix #295

### CODE REVIEW

**Comment by scottinet** [comment]
+1

**Comment by stafyniaksacha** [comment]
Does this fix can have a test ?

**Comment by ballinette** [comment]
@stafyniaksacha Difficult to make an automated test here.
Qerver and worker are launched asycnhronously by the run.sh script within the containers.
To reproduce the bug, we need:
* either to start the environment several times until the worker's startup is finished before the server's one
* or hack the commands/start.js to add a ugly "sleep" instruction at the beginning of the server's startup, to be sure it ends after the worker
* or launch manually the worker, and then the server.

But I'm afraid that it cannot be done by automated unit-tests here (or if someone has a solution, I will be happy to know it ;) )

**Comment by scottinet** [comment]
I don't know if the test is still there, but I remember writing such a test way back.
It went like this:
* stub network connection responding with a ECONNECT error, simulating a connection error
* verify that the client tries to reconnect by itself

It was done with ugly handmade mocks of course. :smile: 
Using sinon stubs and fake timers the test should be lighter than what I wrote at the time. 

What do you think?

**Comment by ballinette** [comment]
@scottinet In fact, I see no unit tests for commands/ directory... but we can try your solution ;)

**Comment by ballinette** [comment]
Sorry, my bad, I was looking at the bin/command/start.js script, but what we have to test here is the internalBroker, and there still are tests in test/services/implementations/broker.test.js

So I just have to add your suggestion within...

**Comment by ballinette** [comment]
This will have to be merged within release 1.0.0-RC3, So I created a new PR on the release branch:
#311

**Pull request closed without merging**
