### PR TITLE
Https for development stack

### PR DESCRIPTION
**Pull request by benoitvidis**
This PR adds an https endpoint to the development stack on the 7443 port.

The certificates are privately signed, using provided CA certificate.
Domains accepted:
- localhost
- *.kuzzle.loc

You'll need to import the CA certificate to your browser and possibly your system local authorities to make it verified.
Once done, your browser should not complain when reaching https://localhost:7443

Using node.js, for instance when using the sdk, you'll need to pass the CA cert using an environment variable:

```
NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/kuzzleCA.crt wscat -c wss://localhost:7443
```

### CODE REVIEW

**Comment by scottinet** [comment]
Can you add a new chapter to the README file with (more or less) your PR description, to explain how to use SSL during development?

(or maybe in a new dedicated README file?)

**Comment by alexandrebouthinon** [comment]
@scottinet: Contributing should be the best choice for that information

**Comment by Aschen** [comment]
Nice work! I will add this features to plugin boilerplates once this PR is merged

**Comment by Aschen** [comment]
I added an entry in CONTRIBUTING about Kuzzle over SSL

**Comment by benoitvidis** [comment]
Thank you @Aschen :)

**Comment by alexandrebouthinon** [comment]
I think we can merge it now :slightly_smiling_face:

**Pull request merged**
